### ISSUE TITLE
Example "Finding paths/values according to a filter" doesn't compile

### ISSUE THREAD

**Issue by metasim** [mandubian/play-json-zipper#10]
When trying to run the example in the title I get this error:

```
 Error:Error:line (15)missing parameter type for expanded function ((x$1) => x$1.$eq$eq(JsString("TO_FIND")))
js.findAll( _ == JsString("TO_FIND") ).toList
            ^
```

**Comment by mandubian** [comment]
have you tried specifying a param?

```scala
js.findAll( a => a == JsString("TO_FIND") ).toList
```

**Comment by MaggieLeber** [comment]
I think @metasim  is saying the *example* doesn't compile. 

And your suggestion 

```js.findAll( a => a == JsString("TO_FIND")).toList```

for me gives 

`Type mismatch, expected: (JsPath, JsValue) => Boolean, actual: (Nothing) => Boolean`

This seems to work though:  

```js.findAll( (a:JsPath,b:JsValue) => b == JsString("TO_FIND") ).toList```

**Comment by mandubian** [comment]
Thanks a lot for the precision...
I just read the error and gave a simple hint but I couldn't spend time to
look at the API itself (which is quite lazy coming from myself who wrote
this code :D)

PR are welcome naturally & even committers!
